# Pandas核心数据结构/类

### 核心数据结构：Series和Dataframe，用来组织和存放数据

# Series数据类型

In [ ]:
'''
Series可以理解为一行或一列数据，类似于一维数组，由索引index和值value组成
在Pandas中其实是没有行的概念的，任何数据取出来都是以列的形式
'''
import pandas as pd
import numpy as np

## 创建Series对象

In [ ]:
#自定义Series对象
s1=pd.Series([1,2,3,4,5])   #没有写index，就会默认自增索引
print(s1)

In [ ]:
#自定义Series对象，采用自定义索引
s2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])   #列表形式，常用形式
s22=pd.Series([i for i in range(5)],index=['a','b','c','d','e'])    #列表推导式
print(s22)

In [ ]:
#自定义Series对象，采用元组形式
s3=pd.Series((1,2,3,4,5),index=('a','b','c','d','e'))   #元组形式，元组是不可变对象，传给pandas之后，会被转换成index对象
print(s3)
#自定义Series对象，采用词典形式
s4=pd.Series({'a':1,'b':2,'c':3,'d':5})   #词典形式
print(s4)

In [ ]:
#采用numpy创建Series对象
s5=pd.Series(np.arange(5))
print(s5)

## Series对象的属性

In [ ]:
#构建Series对象
s6=pd.Series(data=[i for i in range(6)],index=[j for j in 'ABCDEF'])    #列表推导式
print(s6)

In [ ]:
#获取Series对象的索引列
print(s6.index)

In [ ]:
#获取Series对象的值
print(s6.values)

In [ ]:
#根据索引获取元素
print(s6['D'])

In [ ]:
#根据索引修改Series对象的元素值
s6['A']=39
print(s6)

# Dataframe数据类型

In [ ]:
#Dataframe是一个类似于二维数组或表格的对象，即有行索引（index），又有列索引（solumns）
#axis=0，代表行索引，sum(axis=0)代表，按上下的方向求和，最后得到一行，axis=1则代表按左右的方向进行操作，最后得到一列

## 创建Dataframe对象

In [ ]:
#采用字典+列表形式创建，在字典里面嵌套列表 （最推荐）
info = {
    '姓名':['zbw','xjx','myy','shy'],
    '年龄':[18,18,18,18],
    '性别':['男','女','男','女'],
}
#将上述数据封装成Dataframe对象
d1=pd.DataFrame(data=info,index=['a','b','c','d'])  #默认情况下，字典的键名就是列名，值就是列数据
print(d1)

In [ ]:
#字典套字典套列表
info={'a':{'姓名':'zbw','年龄':18,'性别':'男'},
      'b':{'姓名':'myy','年龄':18,'性别':'男'},
      'c':{'姓名':'xjx','年龄':18,'性别':'女'},        #字典套字典的情况下，外层字典的键名为列名。内层字典的键名为行名,一个内层字典就是一列数据
}
d2=pd.DataFrame(data=info)
print(d2)

In [ ]:
#列表套元组、列表套列表
info=[['zbw',18,'nan'],
      ['myy',18,'nan'],
      ['xjx',18,'nv'],
]
info=[  ('zbw',18,'nan'),
        ('myy',18,'nan'),
        ('xjx',18,'nv'),
]
d3=pd.DataFrame(data=info,index=['a','c','b'],columns=['姓名','年龄','性别'])
print(d3)

In [ ]:
#通过numpy的ndarray对象，创建Dataframe对象
#创建ndarray对象
a1=np.arange(0,12).reshape(3,4)
print(a1)
d4=pd.DataFrame(data=a1,index=[1,2,3],columns=['a','b','c','d'])
print(d4)

## Dataframe数据类型简单案例

In [ ]:
#生成10名同学5门功课的成绩，范围40-100
info=np.random.randint(40,101,(10,5))   #左闭右开
print(info)

In [ ]:
#封装为Dataframe对象
score_list=pd.DataFrame(info)
print(score_list)

In [ ]:
#修改索引和列名字
column_names=['语文','数学','英语','物理','化学']
index_names=['同学'+str(i) for i in range(1,score_list.shape[0]+1)]
#方法1
# score_list.index=index_names
# score_list.columns=column_names
#方法2,通过rename精准修改，需要传入字典
score_list.rename(columns={i: column_names[i] for i in range(len(column_names))}, index={i: index_names[i] for i in range(len(index_names))}, inplace=True)     #字典推导式 i：column_names[i] for i in 10 字典的键值对都会遍历
# print(score_list)
score_list

In [ ]:
score_list.shape[0]

## dataFrame基本属性

In [ ]:
#基本属性包括：纬度（行列数），索引列，列名，数据，行列转置等等
print('score_list的维度为：',score_list.shape)   #shape属性，返回一个元组，包含行数和列数
print('score_list的行数为：',score_list.shape[0])   #shape属性，返回一个元组，包含行数和列数
print('score_list的列数为：',score_list.shape[1])   #shape属性，返回一个元组，包含行数和列数
print('score_list的索引列为：',score_list.index)   #index属性，返回索引列
print('score_list的列名为：',score_list.columns)   #columns属性，返回列名
print('score_list的数据为：',score_list.values)       #data属性，返回数据
print('score_list的行列转置为：',score_list.T)       #T属性，返回行列转置

## dataFrame基本函数

In [ ]:
#查看前n行数据head(n)，不写n默认是五行
score_list.head(4)

In [ ]:
#查看后n行数据tail(n)，不写n默认是五行
score_list.tail(4)

In [ ]:
#info(),查看数据的详细信息，包括数据类型，非空值数量，内存占用情况等
score_list.info()

In [ ]:
#describe(),查看数据的基本统计信息，包括计数、均值、标准差、最小值、最大值、四分位数等
score_list.describe()

In [ ]:
#reset_index(),重置索引
score_list.reset_index(drop=False,inplace=True)   #drop=False表示保留原来的索引列，inplace=True表示在原来的数据上进行修改
score_list

In [ ]:
#set_index(),重新设置索引
score_list.set_index('语文',inplace=True)   #将语文列设置为索引列
score_list
score_list.info()

# Pandas的数据类型dtype

In [ ]:
#pandas的数据类型和python基本一样，只有几个不同，例如：object对应于python的str类型，np.nan/pd.NA对应于python的None类型，datetime64对应于python的datetime类型，timedelta[ns]对应于python的timedelta类型
#此外，pandas还支持一些特殊的数据类型，例如：category类型，用于表示分类数据，sparse类型，用于表示稀疏数据，interval类型，用于表示区间数据，period类型，用于表示时间段数据，等等

In [ ]:
#创建dataframe对象，演示缺省数据类型
df=pd.DataFrame(
    {'姓名':{'学生1':'zbw','学生2':'myy','学生3':'xjx'},
     '年龄':{'学生1':18,'学生2':18,'学生3':18},
     '性别':{'学生1':'男','学生2':'男','学生3':'女'}
    }
)   #字典套字典形式
df

In [45]:
df2=pd.DataFrame(
    {
        '姓名':['zbw',pd.NA,'xjx'],
        '年龄':[18,np.nan,18],
        '性别':['男','女',None]
    }
)
df2

    姓名    年龄   性别
0  zbw  18.0    男
1  NaN   NaN    女
2  xjx  18.0  NaN

In [56]:
#演示日期时间数据类型，日期时间的常用定义格式为：xxxx-xx-xx xx:xx:xx
df3=pd.DataFrame(['2024-2-18 00:30:30','2026-12-6'], dtype='datetime64[ns]') #日期时间类型必须严格遵守现实的日期时间格式，否则会报错
df3

                    0
0 2024-02-18 00:30:30
1 2026-12-06 00:00:00

In [66]:
#演示时间差timedelta类型，时间差的常用定义格式为：xx days xx:xx:xx
df4=pd.to_datetime(['2025-2-18 00:30:56'])
df4 #默认只显示最后一个表达式，后面还有语句运行就不显示
print(df4.dtype)

df5=pd.to_datetime(['2026-10-10 15:38:36'])
df5
df6=df5-df4
print(df6)
print(df6.dtype)

datetime64[us]
TimedeltaIndex(['599 days 15:07:40'], dtype='timedelta64[us]', freq=None)
timedelta64[us]